### ISSUE TITLE
Method Woo\GridView\View::__toString() 

### ISSUE THREAD

**Issue by amirajlo** [deniskoronets/Laravel-GridView#1]
Method Woo\GridView\View::__toString() must not throw an exception, caught Error: Cannot use object of type Woo\GridView\Actions as array

**Comment by deniskoronets** [comment]
sorry, this package is still in development :(

**Comment by andymage** [comment]
Method Woo\GridView\View::__toString() must not throw an exception, caught Error: Cannot use object of type Woo\GridView\Actions as array Still the error?

**Comment by deniskoronets** [comment]
Please check, rendering is different now, instead of toString usage, ->render() should be called.
