### ISSUE TITLE
Пагинация и сортировка между собой никак не взаимодействую

### ISSUE THREAD

**Issue by Michael-74** [deniskoronets/Laravel-GridView#10]
Здравствуйте!
Спасибо за компонент, однозначно звезда в репозиторий.
Но хотелось бы видеть взаимодействие пагинации и сортировки.
А то сейчас получается что пагинация сбрасывает отсортированные данные.

**Comment by deniskoronets** [comment]
Сортировка перестраивает список в другом порядке, посему будет мало смысла от того что пользователь будет на 5ой странице с абсолютно другими записями.

**Comment by deniskoronets** [comment]
Закрываю проблему в следствиии отсутствия дальнейших вопросов.
