### ISSUE TITLE
Few examples , Help wanted

### ISSUE THREAD

**Issue by MmKargar** [deniskoronets/Laravel-GridView#14]
laravel : `7.29.3`
laravel-gridview : `2.1`

thanks for great GridView. 👍 
Wish you made more examples and have more documentary.
I can't figure out how to use variables in view column , or how can i set items in dropdown filter.
i didn't find an example for this.
and in this example:
```
        [
            'value' => 'is_active',
            'filter' => [ // by default, TextFilter is used, but you may override with any other
                'class' => 'dropdown',
                'items' => [
                    'Y' => 'Yes',
                    'N' => 'No',
                ]
            ]
        ],
```
what if i want to use something like this `Province::pluck('id','name')` in items section?
and if i set an `title` its give me an error.

**Comment by deniskoronets** [comment]
items may be any array with key => value pairs
