### ISSUE TITLE
How to add keyword of search to pagination link?

### ISSUE THREAD

**Issue by n2bang** [deniskoronets/Laravel-GridView#16]
As example apply gridview category page:
- Search form input a keyword
- Results have a pagination
- After click to pager than number 1 then the result was reseted at the begin
<img width="1557" alt="pagination" src="https://user-images.githubusercontent.com/11874702/108225188-47361500-716e-11eb-823f-b28b8418270c.png">

**Comment by deniskoronets** [comment]
Could you please explain in more details what you want to do?

**Comment by n2bang** [comment]
> Could you please explain in more details what you want to do?

I've already wrote more detail.

**Comment by deniskoronets** [comment]
please use now dev-master, this had been fixed but not yet released into 2.x version

**Comment by n2bang** [comment]
Thanks for your information! Sorry I've already replied late.
