### ISSUE TITLE
must be an instance of Illuminate\Database\Eloquent\Builder....

### ISSUE THREAD

**Issue by baradhili** [deniskoronets/Laravel-GridView#2]
running into this error
`Argument 1 passed to Woo\GridView\DataProviders\EloquentDataProvider::__construct() must be an instance of Illuminate\Database\Eloquent\Builder, instance of Illuminate\Database\Eloquent\Collection given, called in /home/vagrant/code/app/Http/Controllers/PagesController.php on line 32`

PagesController looks like this:-

`<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Item;
use Illuminate\Database\Eloquent\Builder;
use \Woo\GridView\DataProviders\EloquentDataProvider;

class PagesController extends Controller
{
    /**
     * Homepage
     *
     * @return \Illuminate\Http\Response
     */
    public function home()
    {
        return view('welcome');
    }

    /**
     * Dashboard
     *
     * @return \Illuminate\Http\Response
     */
    public function dashboard()
    {
        return view('dashboard.main', [
			'dataProvider' => new EloquentDataProvider(Item::all())
		]);
    }
}`

For the life of me I can't work out what is happening .. help?

**Comment by deniskoronets** [comment]
EloquentDataProvider expects query Builder instance in constructor, not a Collection one. `all()` returns collection. Generally, the basic idea is that you should provide query instance instead of resulting data. Data provider will extract the data by itself. In your case, this will work:
```
new EloquentDataProvider(Item::query())
```
