### ISSUE TITLE
Tests array has failed on Woo\GridView\Columns\ActionsColumn::value: Property should be an array 

### ISSUE THREAD

**Issue by vishalsinhadev** [deniskoronets/Laravel-GridView#4]
I am using an action column in this way :

        [
            'class' => 'actions',
            'value' => '{show} {update}',
            'actionsUrls' => function($model) {
                return [
                    'show' => route('course.show', ['id' => $model->id]),
                    'update' => route('course.edit', ['id' => $model->id])
                ];
            }
        ]

But I am getting an error : 

Tests array has failed on Woo\GridView\Columns\ActionsColumn::value: Property should be an array

**Comment by deniskoronets** [comment]
Good day, Sir! Which package version do you use? You seem read docs for v1.x but used 2.x, which have totally different action columns. Take a look here: https://deniskoronets.github.io/Laravel-GridView/getting-started

Now, action column has actions inside so in value you have to specify a list of actions:
```php
[
    'class' => 'actions', // class option allows to change column class
    'value' => [
        'edit:/path/to/{id}', // {id} - will be replaced with an attribute from row
        'view:/path/{id}',
        'delete:/path/to/{id}',
        new \Woo\GridView\Columns\Actions\Action('copy/{id}', '<i class="fa fa-copy"></i>'),
    ]
]
```

**Comment by deniskoronets** [comment]
In your case it should look like this:
```php
[
    'class' => 'actions', 
    'value' => [
        'edit:' . route('course.edit', ['id' => '{id}']),
        'view:' . route('course.show', ['id' => '{id}']),      
    ]
]
```
Let me know if you have any issues with it

**Comment by vishalsinhadev** [comment]
well, thanks, I followed the different documentation, I think you need to add this in the documentation.
This package is really a great way for integration just like Yii2 grid view.  This package just needs proper documentation for implementation.

**Comment by deniskoronets** [comment]
It has proper documentation by this url: https://deniskoronets.github.io/Laravel-GridView/

**Comment by vishalsinhadev** [comment]
Thanks @deniskoronets

**Comment by Sirick93** [comment]
I followed the installation and also stumbled across this same error. @vishalsinhadev is right. It should be mentioned somewhere cause it took a while to solve.
