### ISSUE TITLE
Doenst work on PHP 8

### ISSUE THREAD

**Issue by juniorari** [deniskoronets/Laravel-GridView#49]
This great repository doenst work yet on PHP 8? :(

**Comment by deniskoronets** [comment]
I want to do some work on this package to clean it up. It will support php 7-8 but later

**Comment by juniorari** [comment]
If you need help @deniskoronets , i can help you! !

**Comment by deniskoronets** [comment]
@juniorari please use `dev-master` version for now. It works with php8 just fine!
