### ISSUE TITLE
The action column is not getting rendered 

### ISSUE THREAD

**Issue by harlangray** [deniskoronets/Laravel-GridView#5]
![image](https://user-images.githubusercontent.com/9457042/66196340-af03d100-e6db-11e9-94cc-9e21ba644a92.png)

**Comment by deniskoronets** [comment]
Please show your code which renders the table

**Comment by harlangray** [comment]
Thanks for the reply. I got it working thanks. I had used 
'formatters' => ['text'], It worked when I removed that line. 

thanks

**Comment by deniskoronets** [comment]
action column formatter by default has no formatters which makes it render raw html. You shouldn't add any formatter to this type of column.
